### ISSUE TITLE
Support Brick v1.2

### ISSUE THREAD

**Issue by s0301132** [BrickSchema/reconciliation-api#4]
Hi @gtfierro, can I configure the server to make the reconcile services using Brick version 1.2 ? Since my iBMS point have some condenser sensor which only included in version 1.2, thanks!

**Comment by gtfierro** [comment]
Yes, this should be possible! If you update the `brickschema` dependency to at least 0.4.1 that should be sufficient; alternatively, you can also supply the `brick_version` argument to the [TagInferenceSession](https://brickschema.readthedocs.io/en/latest/source/brickschema.html#brickschema.inference.TagInferenceSession) that is instantiated inside the `app.py` file. Let me know if you run into any issues!

**Comment by s0301132** [comment]
@gtfierro Thanks for your reply, after setting to version 1.2 it still can't reconcile the condenser type tag, I lookup the source file of `TagInferenceSession` , should I edit the `taglookup.pickle` file to make it easier to reconcile condenser?

**Comment by gtfierro** [comment]
@s0301132 I think that may be on me. Can you try instaling `brickschema==0.4.2a1` to see if that fixes the issue? I have rebuilt the taglookup.pickle file in that alpha release

**Comment by s0301132** [comment]
@gtfierro I can't find that alpha build `0.4.2a1` with latest pip version.

`(venv) PS C:\Users\chihungchung\Desktop\reconciliation-api-main> pip install brickschema==0.4.2a1
ERROR: Could not find a version that satisfies the requirement brickschema==0.4.2a1 (from versions: 0.0.1a0, 0.0.1a1, 0.0.1a2, 0.0.1a3, 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.1.0, 0.1.1a1, 0.1.1a2, 0.1.1, 0.1.2a1, 0.1.2a2, 0.1.2a3, 0.1.2, 0.1.3, 0.1.4a1, 0.1.4, 0.1.5a1, 0.1.5a2, 0.1.5, 0.1.6, 0.1.7a1, 0.1.7a2, 0.1.7a3, 0.1.7a4, 0.1.7a5, 0.1.7a6, 0.1.7, 0.1.8a1, 0.1.8a2, 0.1.8a3, 0.1.8a4, 0.1.8a5, 0.1.8a6, 0.1.8, 0.1.9a1, 0.1.9, 0.1.10, 0.1.11a1, 0.1.11a2, 0.1.11a3, 0.1.11a4, 0.1.11a5, 0.1.11, 0.2.0a1, 0.2.0a2, 0.2.0a3, 0.2.0a4, 0.2.0a5, 0.2.0a6, 0.2.0a7, 0.2.0a8, 0.2.0a9, 0.2.0, 0.2.1a1, 0.2.1a2, 0.2.1, 0.2.2, 0.2.3a1, 0.2.3a2, 0.2.3a3, 0.2.3a4, 0.2.3a5, 0.2.3a6, 0.2.3a7, 0.2.3a8, 0.2.3, 0.2.4a1, 0.2.4a2, 0.2.4, 0.2.5a1, 0.2.5a2, 0.2.5a3, 0.2.5, 0.2.6a1, 0.2.6a2, 0.2.6a3, 0.2.6a4, 0.3.0a1, 0.3.0a2, 0.3.0a3, 0.3.0a4, 0.3.0a5, 0.3.0a6, 0.3.0a7, 0.3.0a8, 0.3.0a9, 0.3.0, 0.3.1, 0.3.2a1, 0.3.2, 0.3.3, 0.3.4, 0.4.0, 0.4.1a1, 0.4.1a2, 0.4.1a3, 0.4.1a4, 0.4.1a5, 0.4.1a6, 0.4.1a7, 0.4.1a8, 0.4.1a9, 0.4.1a10, 0.4.1a11, 0.4.1a12, 0.4.1a13, 0.4.1a14, 0.4.1)
ERROR: No matching distribution found for brickschema==0.4.2a1
(venv) PS C:\Users\chihungchung\Desktop\reconciliation-api-main> pip install --upgrade pip
Requirement already satisfied: pip in c:\users\chihungchung\desktop\reconciliation-api-main\venv\lib\site-packages (21.1.3)`

**Comment by gtfierro** [comment]
So sorry about that... it actually should be published now (https://pypi.org/project/brickschema/0.4.2a1/)

**Comment by s0301132** [comment]
Thanks @gtfierro, now it can identify both chiller and condenser tag.
