### ISSUE TITLE
Missing rdf namespace

### ISSUE THREAD

**Issue by s0301132** [BrickSchema/reconciliation-api#5]
Hi @gtfierro, when I use `make.py` to convert, the ttl file are missing `rdf` namespace even I put it in template txt, the output ttl file only have `brick` and `building` namespace.

**Comment by gtfierro** [comment]
The RDFlib serialization I believe will skip any namespaces that aren't used in the output. Statements like `bldg:x a brick:Sensor` *technically* use the `rdf` namespace (`a` is an alias for `rdf:type`), but this gets factored out during the export process. Does this match what you are seeing, or are there triples with `rdf:****` in the output TTL file?

**Comment by s0301132** [comment]
@gtfierro yes, the output ttl file use something like `bldg:x a brick:Sensor` instead of `rdf:type`, in my `template.txt` I use rdf like `wkgo:$3 rdf:type brick:Main_Header_Pipe` but the output still missing rdf namespace.

**Comment by gtfierro** [comment]
Sounds like this is the RDFlib serialization implementation; the `a` token is [part of the Turtle spec](https://www.w3.org/TR/turtle/#iri-a) so this is technically valid output. Any compliant turtle file parser should be able to parse the output file correctly and recognize `a` as `rdf:type`

**Comment by s0301132** [comment]
That's OK since the builder can convert `rdf:type` to `a`, may be I need to add the rdf namespace in GraphDB.

**Comment by gtfierro** [comment]
I think adding the `rdf` namespace to GraphDB is a good idea. However, to be clear, `a` is equivalent to `rdf:type` (no conversion is performed), and this is done by RDFlib, not by brick-builder. Are you running into any issues with the TTL files produced by brick-builder?

**Comment by s0301132** [comment]
Thanks @gtfierro, there are no issue whille converting, knowing the rdf namespace is not a issue by brick-builder and everything is fine. Thanks!
